#@author cong@cannabis.wiki
#Horozontal pod scalar
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bbb-pod-scaler
  namespace : bbb
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: bbb
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  # behavior:
  #   scaleDown:
  #     selectPolicy: Disabled