apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bbb
  namespace: bbb
spec:
  serviceName: "bbb"
  replicas: 1
  selector:
    matchLabels:
      app: bbb
  template:
    metadata:
      labels:
        app: bbb
    spec:
      hostNetwork: true
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "mongodb"
        - "redis"
        - "bbb-web"
        - "bbb-freeswitch"
        - "bbb-webrtc-sfu"
        - "bbb-nginx"
        - "bbb-fsesl-akka"
        - "fsesl-akka"
        - "bbb-jodconverter"
        - "bbb-periodic"
        - "host.docker.internal"
        - "html5"
        - "etherpad"
        - "webrtc-sfu"
        - "jodconverter"
        - "bbb-apps-akka"
        - "apps-akka"
      containers:
        - name: bbb-html5-backend
          image: destinyakpo/bbb-docker-html5:v2.7.3
          imagePullPolicy: Always
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: DOMAIN
            - name: CLIENT_TITLE
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: CLIENT_TITLE
            - name: ETHERPAD_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: ETHERPAD_API_KEY
            - name: LISTEN_ONLY_MODE
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: LISTEN_ONLY_MODE
            - name: DISABLE_ECHO_TEST
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: DISABLE_ECHO_TEST
            - name: AUTO_SHARE_WEBCAM
              value: "false"
            - name: DISABLE_VIDEO_PREVIEW
              value: "false"
            - name: CHAT_ENABLED
              value: "true"
            - name: CHAT_START_CLOSED
              value: "false"
            - name: BREAKOUTROOM_LIMIT
              value: "8"
            - name: DEV_MODE
              value: "-"
            - name: BBB_HTML5_ROLE
              value: backend
            - name: PORT
              value: "4000"
            - name: INSTANCE_ID
              value: "1"
            - name: MONGO_OPLOG_URL
              value: "mongodb://127.0.0.1:27017/local"
            - name: MONGO_URL
              value: "mongodb://127.0.0.1:27017/meteor"
            - name: ROOT_URL
              value: "http://127.0.0.1/html5client"
            - name: NODE_ENV
              value: "production"
            - name: SERVER_WEBSOCKET_COMPRESSION
              value: '{"level":5, "maxWindowBits":13, "memLevel":7, "requestMaxWindowBits":13}'
            - name: BIND_IP
              value: "127.0.0.1"
            - name: LANG
              value: "en_US.UTF-8"
            - name: INSTANCE_MAX
              value: "1"
            - name: ENVIRONMENT_TYPE
              value: "production"
            - name: NODE_VERSION
              value: "node-v14.21.1-linux-x64"
            - name: BBB_HTML5_LOCAL_SETTINGS
              value: "/app/bbb-html5.yml"
          volumeMounts:
            - mountPath: /html5-static
              name: bbb-volume

        - name: bbb-html5-frontend
          image: destinyakpo/bbb-docker-html5:v2.7.3
          imagePullPolicy: Always
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: DOMAIN
            - name: CLIENT_TITLE
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: CLIENT_TITLE
            - name: ETHERPAD_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: ETHERPAD_API_KEY
            - name: LISTEN_ONLY_MODE
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: LISTEN_ONLY_MODE
            - name: DISABLE_ECHO_TEST
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: DISABLE_ECHO_TEST
            - name: AUTO_SHARE_WEBCAM
              value: "false"
            - name: DISABLE_VIDEO_PREVIEW
              value: "false"
            - name: CHAT_ENABLED
              value: "true"
            - name: CHAT_START_CLOSED
              value: "false"
            - name: BREAKOUTROOM_LIMIT
              value: "8"
            - name: DEV_MODE
              value: "-"
            - name: BBB_HTML5_ROLE
              value: frontend
            - name: INSTANCE_ID
              value: "1"
            - name: MONGO_OPLOG_URL
              value: "mongodb://127.0.0.1:27017/local"
            - name: MONGO_URL
              value: "mongodb://127.0.0.1:27017/meteor"
            - name: ROOT_URL
              value: "http://127.0.0.1/html5client"
            - name: NODE_ENV
              value: "production"
            - name: SERVER_WEBSOCKET_COMPRESSION
              value: '{"level":5, "maxWindowBits":13, "memLevel":7, "requestMaxWindowBits":13}'
            - name: BIND_IP
              value: "127.0.0.1"
            - name: LANG
              value: "en_US.UTF-8"
            - name: INSTANCE_MAX
              value: "1"
            - name: ENVIRONMENT_TYPE
              value: "production"
            - name: NODE_VERSION
              value: "node-v14.21.1-linux-x64"
            - name: BBB_HTML5_LOCAL_SETTINGS
              value: "/app/bbb-html5.yml"
          volumeMounts:
            - mountPath: /html5-static
              name: bbb-volume

        - name: bbb-web
          image: destinyakpo/bbb-docker-web:v2.7.3
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - wget
                - --no-verbose
                - --tries=1
                - --spider
                - http://127.0.0.1:8090/bigbluebutton/api
            initialDelaySeconds: 120
          resources: {}
          volumeMounts:
            - mountPath: /var/bigbluebutton
              name: bbb-volume
            - mountPath: /var/freeswitch/meetings
              name: bbb-volume
            - mountPath: /var/kurento
              name: bbb-volume
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: DOMAIN
            - name: SHARED_SECRET
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: SHARED_SECRET
            - name: DEV_MODE
              value: "false"
            - name: ENABLE_RECORDING
              value: "false"
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: WELCOME_MESSAGE
            - name: WELCOME_FOOTER
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: WELCOME_FOOTER
            - name: STUN_SERVER
              value: "stun:80.158.111.32:3478"
            - name: TURN_SERVER
              value: "turns:srv02.bbb.t-assets.de:5349?transport=tcp"
            - name: TURN_SECRET
              value: "S9DGGXMHX0Z483bLYbCFM8HAGQ92IZP1"
            - name: NUMBER_OF_BACKEND_NODEJS_PROCESSES
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: NUMBER_OF_BACKEND_NODEJS_PROCESSES
            - name: LEARNING_DASHBOARD_ENABLED
              value: "true"

        - name: bbb-freeswitch
          image: destinyakpo/bbb-docker-freeswitch:v1.10.10-v2.7.3
          imagePullPolicy: Always
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: DOMAIN
            - name: EXTERNAL_IPv4
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: EXTERNAL_IPv4
            - name: ESL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: FSESL_PASSWORD
            - name: DISABLE_SOUND_MUTED
              value: "true"
            - name: DISABLE_SOUND_ALONE
              value: "true"
            - name: SOUNDS_LANGUAGE
              value: en-us-callie
          resources: {}
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - NET_ADMIN
                - NET_RAW
                - NET_BROADCAST
                - SYS_NICE
                - SYS_RESOURCE
          volumeMounts:
            - mountPath: /etc/freeswitch/sip_profiles/external
              name: bbb-volume
            - mountPath: /etc/freeswitch/dialplan/public_docker
              name: bbb-volume
            - mountPath: /var/freeswitch/meetings
              name: bbb-volume

        - name: bbb-nginx
          image: destinyakpo/bbb-docker-nginx:1.23-v5.0.2-v2.7.3
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/bigbluebutton
              name: bbb-volume
            - mountPath: /html5-static
              name: bbb-volume
              readOnly: true
            - mountPath: /www/
              name: bbb-volume
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              name: nginx-config
          ports:
            - containerPort: 8080

        - name: etherpad
          image: destinyakpo/bbb-docker-etherpad:1.9.1-s8328b77-p068ded5
          imagePullPolicy: Always
          env:
            - name: ETHERPAD_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: ETHERPAD_API_KEY

        - name: redis
          image: redis:7.2-alpine
          imagePullPolicy: Always

        - name: kurento
          image: kurento/kurento-media-server:6.18
          imagePullPolicy: Always
          env:
            - name: STUN_IP
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: STUN_IP
            - name: STUN_PORT
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: STUN_PORT
          volumeMounts:
            - mountPath: /var/kurento
              name: bbb-volume

        - name: bbb-webrtc-sfu
          image: destinyakpo/bbb-docker-webrtc-sfu:v2.12.0
          imagePullPolicy: Always
          env:
            - name: CLIENT_HOST
              value: "0.0.0.0"
            - name: KURENTO_NAME
              value: kurento
            - name: REDIS_HOST
              value: redis
          volumeMounts:
            - name: webrtc-sfu-log
              mountPath: /var/log/bbb-webrtc-sfu

        - name: bbb-fsesl-akka
          image: destinyakpo/bbb-docker-fsesl-akka:v2.7.3
          imagePullPolicy: Always
          env:
            - name: FSESL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: FSESL_PASSWORD

        - name: bbb-apps-akka
          image: destinyakpo/bbb-docker-apps-akka:v2.7.3
          imagePullPolicy: Always
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: DOMAIN
            - name: SHARED_SECRET
              valueFrom:
                configMapKeyRef:
                  name: bbb-config
                  key: SHARED_SECRET
          volumeMounts:
            - mountPath: /var/freeswitch/meetings
              name: bbb-volume

        - name: bbb-jodconverter
          image: destinyakpo/bbb-docker-jodconverter:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              value: "8081"
          ports:
            - containerPort: 8081

        - name: bbb-periodic
          image: destinyakpo/bbb-docker-periodic:v2.7.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/bigbluebutton
              name: bbb-volume

        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017
          imagePullPolicy: IfNotPresent
          resources: {}
          volumeMounts:
            - mountPath: /data/configdb
              name: mongodb-tmpfs0
            - mountPath: /data/db
              name: mongodb-tmpfs1
            - name: mongo-config
              mountPath: /etc/mongod.conf
              subPath: mongod.conf
            - name: mongo-config
              mountPath: /docker-entrypoint-initdb.d/init-replica.sh
              subPath: init-replica.sh

      restartPolicy: Always
      volumes:
        - name: bbb-volume
          hostPath:
            path: /var/bbb-volume
            type: DirectoryOrCreate

        - emptyDir:
            medium: Memory
          name: mongodb-tmpfs0

        - emptyDir:
            medium: Memory
          name: mongodb-tmpfs1

        - emptyDir:
            medium: Memory
          name: recordings-tmpfs0

        - emptyDir:
            medium: Memory
          name: recordings-tmpfs1

        - emptyDir:
            medium: Memory
          name: resty-auto-ssl

        - name: ssl-volume
          hostPath:
            path: /var/resty-auto-ssl
            type: DirectoryOrCreate

        - name: mongo-config
          configMap:
            defaultMode: 0777
            name: mongo-config
            items:
            - key: mongod.conf
              path: mongod.conf
            - key: init-replica.sh
              path: init-replica.sh

        - name: nginx-config
          configMap:
            name: nginx-config

        - name: webrtc-sfu-log
          emptyDir: {}

  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
