apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bbb-pod-scaler
  namespace: bbb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: bbb
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
